[versions]
agp = "8.7.0"
kotlin = "2.0.21"
androidx-compose = "1.7.3"
activy-compose = "1.9.2"
material3 = "1.3.0"
material = "1.12.0"
core-ktx = "1.13.1"
espresso-core = "3.6.1"
lifecycle-runtime-ktx = "2.8.6"
datastore-preferences = "1.1.1"
ext-junit = "1.2.1"
junit  = "4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }


[libraries]
activity-compose = {module = "androidx.activity:activity-compose", version.ref = "activy-compose" }
compose_ui = {module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
core-ktx = {module = "androidx.core:core-ktx", version.ref = "core-ktx" }
espresso-core = {module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core"}
ext-junit = {module = "androidx.test.ext:junit", version.ref = 'ext-junit'}
lifecycle-runtime-ktx = {module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx"}
material = {module = "com.google.android.material:material", version.ref = "material"}
material3 = {module = "androidx.compose.material3:material3", version.ref = "material3"}
material3-window-size = {module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3"}
datastore-preferences = {module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences"}
ui-test-junit4 = {module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose" }
junit =  {module = "junit:junit", version.ref = "junit"}
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }